### ISSUE TITLE
clock is outdated

### ISSUE THREAD

**Issue by thebetterjort** [Renovamen/playground-macos#5] opened 2021-05-08 17:15 UTC
Your setInterval on your new Date in state doesnt seem to be working. Clock is out of date.

**Comment by Renovamen** [comment] 2021-05-09 08:02
Fixed in [98c41be](https://github.com/Renovamen/playground-macos/commit/98c41beb1e4d9765aa52daad0c363ade754f70e2). This issue is caused by a typo in code. Thanks!

**Closed** 2021-05-09 08:40 UTC
Labels: bug
