### ISSUE TITLE
Resizing the safari window beyond some size pulls in the wallpaper

### ISSUE THREAD

**Issue by vlovich** [Renovamen/playground-macos#6] opened 2021-05-08 20:14 UTC
As title says, if I resize Safari (only at the initial page), beyond some size the wallpaper is bleeding through instead of it being the default Safari app. I don't think this is the behavior on MacOS but maybe it has changed in the more recent release in which case please ignore.

**Comment by Renovamen** [comment] 2021-05-09 08:45
Hi! Some others have also reported this issue. However, I couldn't reproduce it on my own device (os: macos catalina / windows 10, browser: chrome / firefox / safari), so it bothered me for a while. Would you mind tell me the os and browser you used? Thanks!

**Comment by vlovich** [comment] 2021-05-09 16:45
Chrome on Linux

**Comment by vlovich** [comment] 2021-05-12 17:44
Sorry. I thought I attached the screenshot last time.
![screenshot](https://user-images.githubusercontent.com/201287/118020465-f5390180-b30e-11eb-9d0f-ec7807ea7081.png)

**Comment by vlovich** [comment] 2021-05-12 17:44
The issue disappears once I navigate somewhere.

**Comment by 900eTrip** [comment] 2021-05-27 10:46
> ### ### 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

> **_`[](url)`_**

**Comment by Renovamen** [comment] 2021-05-30 15:05
Hi @vlovich, I think I know where the problem lies, it occurs when the height of the window is very large. I couldn't reproduce it before since my screen is small. Now the problem should be fixed, could you have a look? Thanks!

**Closed** 2021-07-08 15:37 UTC
Labels: bug
